site_name: CCRPC Travel Demand Model Documentation
nav:
  - Documentation: index.md
  - User Guide: userguide.md
theme: 
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  