site_name: CCRPC Travel Demand Model Documentation
nav:
  - Home: index.md
  - User Guide: userguide.md
theme: 
  name: mkdocs
  navigation_depth: 3
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  